### ISSUE TITLE
Convert pulp_deb docs to new stack

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulp_deb#1014]
The general workflow for this task can be found [here](https://hackmd.io/@pbrochad/SyfGeQc86#Content-Migration).

**Comment by pedro-psb** [comment]
Also, you should set `use_unified_docs: true` to get the new docs workflow running on CI:
https://github.com/pulp/pulp_deb/blob/85bc12a8f6d2bea5c4d5daa6930d9913a724b1a5/template_config.yml#L88

**Comment by quba42** [comment]
Link to parent epic: https://github.com/pulp/pulpcore/issues/5037
