### ISSUE TITLE
Publishing a source package that belongs to two dists raises IntegrityError

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp_deb#1053]
Steps to reproduce:
1. Create a source package
2. Add it to two dists in a repo
3. Publish the repo.

You'll get an IntegrityError. Basically the source package publish code needs something similar to this line:

https://github.com/pulp/pulp_deb/blob/106f1489120bebff4bfe012356bdbc8065d8d17b/pulp_deb/app/tasks/publishing.py#L302

**Comment by quba42** [comment]
Sounds plausible given we had the exact same thing with binary packages.

**Comment by hstct** [comment]
Yea seems like one the things we missed when reviewing the source package PR
