### ISSUE TITLE
Support duplicate content for source debs

### ISSUE THREAD

**Issue by garretwyman** [pulp/pulp_deb#1077]
Pulpcore implemented a feature in 3.22.0 (https://github.com/pulp/pulpcore/pull/3083) making pulp return href of existing content instead of throwing an exception. Currently in pulp_deb that log is used for debs, but not for source debs. 

The request is to handle debs and source debs the same by removing the check that `There is already a DSC file with version`.

**Comment by quba42** [comment]
We generally want the retrieve behavior for all API endpoints, so I have removed the Triage-Needed label.

Thanks for contributing a PR to fix this.
