### ISSUE TITLE
Removing packages from structured publications leaves dangling PRCs

### ISSUE THREAD

**Issue by hstct** [pulp/pulp_deb#1190]
**Describe the bug**
When removing a package from a repository via the `/pulp/api/v3/repositories/deb/apt/modify/` endpoint in a structured publication, the corresponding package release component (PRC) file that references the removed package is not removed as expected.

**To Reproduce**
1. Sync a remote repository to create the initial repository version.
2. Use the `/pulp/api/v3/repositories/deb/apt/modify/` endpoint to remove a specific package from the repository.
3. Inspect the latest repository version and verify that the PRC referencing the removed package is still present in the content units.

**Expected behavior**
When a package is removed via the modify endpoint, the PRC file referencing the package's href should also be removed from the repository version to ensure consistency.

**Comment by quba42** [comment]
Just wanted to expand on why this is a problem: On the publish using structured mode, pulp_deb will loop over the dangling PRC, and pull the removed package back in. This means the published repo will contain the package that the user explicitly removed.
