### ISSUE TITLE
Make various release file fields user configurable

### ISSUE THREAD

**Issue by quba42** [pulp/pulp_deb#449]
**Is your feature request related to a problem? Please describe.**

This feature is intended to provide a long term solution for https://github.com/pulp/pulp_deb/issues/443 while also empowering users to use pulp_deb repos in combination with "APT pinning" and "unattended upgrade" workflows.

**Describe the solution you'd like**

- The upstream Origin, Label, and Version fields should be stored on the release content during sync (if present).
- Users should be able to define their own Origin, Label, and Version values on repositories and/or publications.
- User supplied values trump upstream repo values during publish

If possible, consider the possibility of respecting arbitrary upstream and user supplied release file fields?

**Additional context**

#443 Should provide a backportable bugfix solution for the same problem, while this ticket provides a new design approach as a long term solution.

**Comment by quba42** [comment]
The title of this ticket remains as valid as ever, but the proposed implementation requires significant rethink!

**Comment by quba42** [comment]
`Description` is another Release file field that should be considered as part of this issue.

**Comment by mikalstill** [comment]
@quba42, I'd be happy to take a swing at this one (I am already looking for a starter project to contribute to this plugin), but it is not clear to me from your comment why the design needs a rethink. Is there further information available somewhere else for that?

**Comment by quba42** [comment]
@mikalstill I am afraid, I don't always keep the pulp_deb GitHub issues fully up to date (it's on my todo list), because we also use an internal issue tracker in addition to this one. "The design issues" I allude to in this thread are not reflected in an issue right now (I will open one today and link it from this thread). The short version as relates to this issue, is that we no longer want to store any additional fields on the `Release` model. It would probably be safe/fine, to just store them on the `ReleaseFile` model instead though, so that would not be a big difference for how to implement this issue.

**Comment by quba42** [comment]
Note: I have now added an issue for the above mentioned "design issues": https://github.com/pulp/pulp_deb/issues/599

**Comment by eman-koch** [comment]
I upvote this. In our scenario we would like to have all mirrored repositories in pulp made available to the system and then differ what to install with pin-priorities through apt preferences. This makes it easier to manage the systems for us but results in the possibility that we sometimes have 2 or 3 repositories with different versions active, let's take the example with mariadb:

![image](https://user-images.githubusercontent.com/96131915/229139159-c4c2fb29-b2f3-4d76-a37f-a769ee533278.png)

We can't use the filters for neither release/origin as it's the same and thus we would prioritize all repos at the same time. If we can set our own origin or label it would be easy to have this solved.
