### ISSUE TITLE
FORCE_IGNORE_MISSING_PACKAGE_INDICES=True Where does it go?

### ISSUE THREAD

**Issue by saltyollpheist** [pulp/pulp_deb#481]
`No suitable Package index file found in 'dists/focal/main/binary-arm64'. If you are syncing from a partial mirror, try setting ignore_missing_package_indices to 'True' on your remote.`

I'm trying my best to figure out where exactly apply this variable - or preferably its global version `FORCE_IGNORE_MISSING_PACKAGE_INDICES=True` - in order to synchronize my Ubuntu 20.04.4 LTS repository with my Foreman+Katello setup. If someone - anyone - could please elaborate comprehensively where I need to put this variable and how to enable it properly, I would greatly appreciate it.

Foreman+Katello is running on Rocky Linux 8.5 and is able to synchronize with its repository just fine. The only repository I'm having issue with is Ubuntu.

Software and Versions
-
`pulp --version` returns the following:
`pulp3 command line interface, version 0.14.0`
pulpcore-selinux-1.3.0-1.el8.x86_64
python38-pulp-ansible-0.10.1-1.el8.noarch
python38-pulp-certguard-1.5.1-1.el8.noarch
python38-pulp-cli-0.14.0-1.el8.noarch
python38-pulp-container-2.9.2-1.el8.noarch
python38-pulp-deb-2.16.1-1.el8.noarch
python38-pulp-file-1.10.1-1.el8.noarch
python38-pulp-python-3.5.2-1.el8.noarch
python38-pulp-rpm-3.17.3-2.el8.noarch
python38-pulpcore-3.16.6-1.el8.noarch
Katello 4.5.0
Foreman 3.3.0

**Comment by mdellweg** [comment]
I think it should be in the settings. There are multiple ways:
https://docs.pulpproject.org/pulpcore/configuration/applying.html

**Comment by saltyollpheist** [comment]
I had that page pulled up already, but thank you all the same. It doesn't offer a clear, concise answer as to where to place this particular variable. I've tried exporting it as a variable. I've tried putting it in ALL CAPS in the `/etc/pulp/settings.py`. Neither have yielded any change in how Pulp is handling the Ubuntu repository. Further assistance and/or explanation would be much appreciated.

**Comment by maximiliankolb** [comment]
Threads in Foreman Community Forum: [Discrepancies: Ubuntu vs RedHat with Foreman+Katello](https://community.theforeman.org/t/discrepancies-ubuntu-vs-redhat-with-foreman-katello/28191/5?u=maximilian) & [DEB repository synchronization results with Success but no content added](https://community.theforeman.org/t/deb-repository-synchronization-results-with-success-but-no-content-added/28157?u=maximilian)

cc @quba42 and @Manisha15

**Comment by Manisha15** [comment]
You need to restart the pulp services after changing the settings. 

Depending on system you are using:
Either ``sudo systemctl start pulpcore-manager
sudo systemctl start pulp-content``
Or
`prestart`

**Comment by saltyollpheist** [comment]
Replying here as I did on the [Foreman Community](https://community.theforeman.org/t/deb-repository-synchronization-results-with-success-but-no-content-added/28157/10) post for posterity. 

![image](https://user-images.githubusercontent.com/31519460/164261858-3c3ae523-16fc-4b22-9070-17c1df959ffe.png)


Turns out neither of those services are installed, which is a fault of the Foreman+Katello setup as it doesn't mention in its documentation that those services are or are not installed or calls any attention to them whatsoever. So, if those two services are crucial for that variable to be recognized and implemented via `/etc/pulp/settings.py`, it would behoove the Foreman development team to implement those services as part of the setup process.

**Comment by quba42** [comment]
@saltyollpheist Placing `FORCE_IGNORE_MISSING_PACKAGE_INDICES=True` in `/etc/pulp/settings.py` and then running either of the following should work on a Katello installation:
```
systemctl restart pulp*
foreman-maintain service restart
```

**Comment by saltyollpheist** [comment]
Replied in [Foreman Community](https://community.theforeman.org/t/deb-repository-synchronization-results-with-success-but-no-content-added/28157/14?u=saltyollpheist) post regarding these commands and the outcome of both Traditional Method and Flat Repo Format method.

**Comment by saltyollpheist** [comment]
Per the post on the [Foreman Community](https://community.theforeman.org/t/deb-repository-synchronization-results-with-success-but-no-content-added/28157/15?u=saltyollpheist), @quba42 was able to provide me the solution for Ubuntu synchronization. As it stands right now for Ubuntu repository synchronization for anyone who stumbles across this, the following fixed the issue:

1. Append `FORCE_IGNORE_MISSING_PACKAGE_INDICES=True` to `/etc/pulp/settings.py`
2. Run either of the commands as detailed by @quba42 - 
`systemctl restart pulp*  # Will cause running pulp tasks and associated foreman tasks to fail`
`foreman-maintain service restart  # Will take longer, not sure if it protects running tasks from failing`
3. Specify the architecture, even if you need both, as leaving it blank will still cause the sync to fail. Screenshot below for example.

![image](https://user-images.githubusercontent.com/31519460/164316975-0a64b80f-ec1a-4119-bd50-d76d416616c6.png)

Thank you again, @quba42.
