### ISSUE TITLE
Revisit the relative_path package upload design

### ISSUE THREAD

**Issue by Manisha15** [pulp/pulp_deb#543]
At present, it is advised to not modify relative_path and if you do then it should consists of `package name_version` but in some cases, Katello for example, relative_path is set to `filename` which could cause error when uploading the package.

Instead of creating the name ourselves, can we change the design of how relative_path is generated and we can directly use `filename` for it.

**Comment by quba42** [comment]
After some discussions, with upstream, we have decided not to hand control over the relative_path for Debian packages to users, but to change several other things about the upload workflow. I will amend and re-use this ticket for this.

**Comment by quba42** [comment]
After some discussions, with upstream, we have decided not to hand control over the relative_path for Debian packages to users, but to change several other things about the upload workflow.

As a result, I will close this ticket and open up a follow on ticket instead.

**Comment by quba42** [comment]
Follow on task: https://github.com/pulp/pulp_deb/issues/592
