### ISSUE TITLE
Requesting pulp_deb bindings release 2.19.z with updated faraday dependencies

### ISSUE THREAD

**Issue by sjha4** [pulp/pulp_deb#652]
We are planning to upgrade to [pulp_deb_client 2.19.1](https://rubygems.org/gems/pulp_deb_client) as part of upgrading to pulpcore 3.21 but the pulp_deb binding currently has faraday dependencies >= 0.17, < 1.9.0. This conflicts with other plugins being packaged which have faraday dependency as >= 1.0.1, < 2.0.

**Comment by quba42** [comment]
As far as I understood we don't explicitly manage this dependency anywhere, so it should just update automatically whenever we do a 2.19.2 release, which we are planning to do anyway. (I am not sure if or how we can re-release just the bindings for 2.19.1).

**Comment by quba42** [comment]
Note also, that we are also planning to do a 2.20.0 release, which is what we will want to use for Katello with pulpcore 3.21, so we will update to that soon as well.

**Comment by sjha4** [comment]
Thanks for the update @quba42. I wasn't sure if 2.20.0 was being planned soon. We will upgrade to 2.20.0 in that case for Katello 4.7.

**Comment by quba42** [comment]
Update: There is now a `2.19.2` release along with the following client: https://rubygems.org/gems/pulp_deb_client/versions/2.19.2 which has the updated faraday version range.

We also still plan to do a 2.20.0 release today or tomorrow, in case you would rather wait for that.

**Comment by quba42** [comment]
Update: 2.20.0 is out!

With this, I will close this issue. Let me know if there is anything else you need on the Katello side.
