### ISSUE TITLE
PackageReleaseComponents are not being properly handled in the case of duplicates

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp_deb#705]
**Version**
2.20.1

**Describe the bug**
It looks like when a duplicate package gets added to a release in a repository, Pulp properly removes any old duplicate packages (with the same NVA). However, it does not properly remove the PackageReleaseComponents. So if/when the package is removed from the repo, the old package will get published since its PackageReleaseComponent still exists.

**To Reproduce**
1. Upload two packages into Pulp with the same NVA (I'll call them A1 and A2)
2. Create a repo with a release
3. Add A1 to the repo release
4. Add A2 to the repo release
5. Remove A2 from the repo
6. Publish the repo and observe that A1 is in the publication

The problem occurs after step 4. There's only one package in the repo version (correct) but yet there are two PackageReleaseComponents:

```
>>> DebPackage.objects.filter(pk__in=RepositoryVersion.objects.order_by("pulp_created").last().content)
<BulkTouchQuerySet [<Package: azureauth_0.5.4-1_amd64>]>
>>> PackageReleaseComponent.objects.filter(pk__in=RepositoryVersion.objects.order_by("pulp_created").last().content).values_list("pk", "package__package", "package__version", "package__architecture")
<BulkTouchQuerySet [(UUID('aa1ebf24-5c7b-4ef2-baef-9033c5b3b0c4'), 'azureauth', '0.5.4-1', 'amd64'), (UUID('11eeb353-353a-4dd1-aacc-e7c823571207'), 'azureauth', '0.5.4-1', 'amd64')]>
```

**Expected behavior**
If pulp_deb automatically removes the old duplicate package, then I'd argue it should remove the PackageReleaseComponent too. In fact, I think adding a repo_key_fields constraint to PackageReleaseComponent should solve the problem:

```
repo_key_fields = ("release_component", "package__package", "package__version", "package__architecture")
```

**Comment by daviddavis** [comment]
I haven't tested but I would imagine that this issue would exist when syncing content as well.

**Comment by quba42** [comment]
This issue makes perfect sense to me since there is no mechanism that would somehow automatically remove a `PackageReleaseComponent` from a repo version, just because the associated Package was removed.
