### ISSUE TITLE
Please add `names__in` for deb

### ISSUE THREAD

**Issue by Catman155** [pulp/pulp_deb#717]
**Is your feature request related to a problem? Please describe.**
It frustrates me that the plugins for RPM and DEB are so different. If I want to get a set of packages from the api I can't do that for DEB at the moment.

**Describe the solution you'd like**
I would want a names__in field like in the RPM plugin.

**Describe alternatives you've considered**
I looked for similar fields. don't exist, listing the packages and go through them myself is too time expensive.

**Additional context**
pulp 3.18 using the deb and rpm plugins.

**Comment by quba42** [comment]
Could you provide a complete example of what you are doing in the pulp_rpm case. This will make it much easier to evaluate how best to achieve the same thing in pulp_deb, and whether doing so requires a new pulp_deb feature.

**Comment by quba42** [comment]
I am closing this "Wontfix" for now. It can be re-opened if there is a response on what exactly is being requested here.

**Comment by quba42** [comment]
I am closing this "Wontfix" for now. It can be re-opened if there is a response on what exactly is being requested here.
