### ISSUE TITLE
[DESIGN] A phasing effect for publications that were recently served by a distribution.

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulp_deb#911]
Apt-by-hash is supposed to serve files at known locations for some time (order of days) after the corresponding publication has been replaced by a newer version. This can be accomplished by a distribution that can serve multiple publications like overlays, as long as it can be assured that the publications exist sufficiently long.

> It won't you'd need to retain _something_ for this feature to work. But you need to anyway, because serving the by-hash files without the pool (of the same version) is not gaining you much. So let's say, you have a retain count of X, you add new versions no more than once a day, and the distribution serves files from the current and if not found yet publications it was attached to (by increasing age up to X days).
Now you may identify one bad file in the second to latest publication, you definitely need to stop serving right away, you can still delete that publication, and the distribution would immediately forget it (because the join model cascade deletes with the publication).
If you delete the repository, all you are left with is an empty distribution with no faint memory about any publication (as today).

_Originally posted by @mdellweg in https://github.com/pulp/pulp_deb/pull/884#discussion_r1352291358_

**Comment by daviddavis** [comment]
I had a chance think of a design. Feedback welcome.

I'm imagining this will be released as a tech preview and is independent of the APT_BY_HASH feature we introduced.

## Setting

We'll introduce a new setting `PUBLICATION_CACHE_TIME` to enable the content app to serve artifacts from previously distributed publications for a particular distribution for a period of time.

I think minutes probably makes sense and a default of 0 (at least initially). When using APT_BY_HASH, the recommendation should be 4320 minutes (3 days).

## Model

### DistributedPublication
Inherits from ModelBase.
* publication - foreign key, cascade delete
* distribution - foreign key, cascade delete

Whenever a distribution is created/updated and publication_id is set or has changed, it will create a new DistributedPublication with the publication_id.

Whenever a publication is created, it will check for any distributions where repo id matches the publication's repo id. For any match, a new DistributedPublication gets created.

## Content handler

The distribution will have a content handler method to handle requests. When a request comes in, it'll search the artifacts for any completed publication for the particular distribution where `distribution_publication.pulp_created >= datetime.now() - timedelta(minutes=PUBLICATION_CACHE_TIME)`. The artifacts ought to be sorted by `distribution_publication.pulp_created` and the first match gets returned to the user.

If there are no matching distributed_publications or the code fails to find a matching artifact, the method returns letting the content app handle the request.

**Comment by quba42** [comment]
Do we need to somehow discriminate between artifacts that should still be served, and artifacts that should no longer be served?
My understanding was that APT by Hash should keep old metadata, but not necessarily old packages. or did I get that wrong?

**Comment by daviddavis** [comment]
My original thought was that pulp_deb would only serve old by-hash files but @mdellweg made the point that the publication should serve the old artifacts along with the old metadata.

What if we introduce a setting `PUBLICATION_CACHE_PATH_REGEX` that defaults to `.*` and that users can set so they can decide which paths will be served by old publications?

**Comment by mdellweg** [comment]
This all sounds good to me.
However, let's not introduce any new global setting. I believe this "setting" should be on the distribution model (maybe not in the first cut anyway).
