### ISSUE TITLE
pulp_deb serves unpublished content

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp_deb#976]
Steps to reproduce:

1. Create a repo
2. Create a distro that points to your repo
3. Add a content unit to the repo
4. Observe by hitting the content app that the content is being distributed even though it has not been published.

**Comment by quba42** [comment]
That is "interesting". I don't think I have ever considered what happens when distributing something without a publication.

How big of a problem is this?

**Comment by quba42** [comment]
I did not see there was already a PR to go with this issue. Will continue looking at the PR.

**Comment by daviddavis** [comment]
> That is "interesting". I don't think I have ever considered what happens when distributing something without a publication.

I don't think it should be possible to distribute content without a publication for pulp_deb.

> How big of a problem is this?

I think pretty serious. We guarantee our users that packages won't be available to the outside world unless they are explicitly published.
