### ISSUE TITLE
New user question:  How to rollback a debian verbatim distribution ?  (3.43.0 all in one container)

### ISSUE THREAD

**Issue by kxs-jnadeau** [pulp/pulp_deb#982]
Hi,

Im trying to use the repo versioning feature but can't get it to work.  Following the documentation on [promotions](https://docs.pulpproject.org/pulpcore/workflows/promotion.html) :

"Also, to rollback, you can simply point the Staging CentOS distribution to the Publication it was previously pointed at."

Here's how I created the repo

NAME='ubuntu-jammy-amd64-security'
REMOTE_OPTIONS=(
  --url=http://azure.archive.ubuntu.com/ubuntu
  --distribution=jammy-security
  --architecture=amd64
)
pulp deb remote create --name=${NAME} ${REMOTE_OPTIONS[@]}
pulp deb repository create --name=${NAME} --remote=${NAME}
pulp deb repository sync --name=${NAME}
pulp deb publication  -t verbatim create --repository=${NAME}
pulp deb distribution create --name=${NAME} --base-path=${NAME} --repository=${NAME}

I then made an additional sync to have 2 publications.

pulp deb repository sync --name=${NAME}
pulp deb publication  -t verbatim create --repository=${NAME}

But listing my distribution ,  the publication field is null.  Why is that ?

```
$ pulp deb distribution list
[
  {
    "pulp_href": "/pulp/api/v3/distributions/deb/apt/018c5991-d9c8-7c20-8dc5-8065c7fc77fb/",
    "pulp_created": "2023-12-11T15:49:39.913477Z",
    "base_path": "ubuntu-jammy-amd64-security",
    "base_url": "https://pulphostname/pulp/content/ubuntu-jammy-amd64-security/",
    "content_guard": null,
    "hidden": false,
    "pulp_labels": {},
    "name": "ubuntu-jammy-amd64-security",
    "repository": "/pulp/api/v3/repositories/deb/apt/018c5950-4e51-7010-9db1-08f2fa3f3496/",
    "publication": null
  },

```

I thought the rollback would be the following:

pulp deb distribution update --name=${NAME} --publication $VALUE???

But with the current value set to null I figure Im doing this wrong ?

**Comment by quba42** [comment]
I believe by creating your distribution against the repository like so:
```
pulp deb distribution create --name=${NAME} --base-path=${NAME} --repository=${NAME}
```
You have created a distribution that will _always serve the latest publication that has been created for the repository in question_. If you instead want a distribution that serves a _specific publication_ (until you next update it), you should create the publication and distribution something like this:
```
PUBLICATION_HREF=$(pulp deb publication -t verbatim create --repository=${NAME} | jq -r '.pulp_href')
echo ${PUBLICATION_HREF}  # Just to tell what is going on and if the previous command was successfull
pulp deb distribution create --name=${NAME} --base-path=${NAME} --publication=${PUBLICATION_HREF}
```
If you want even more fine grained control over the publication you are creating, you can also use the `--version <version_number>` parameter along with the `pulp deb publication -t verbatim create` command to create your publication from a specific repository version (rather than the latest version).

**Comment by kxs-jnadeau** [comment]
Thanks for the hint.  For the resync or rollback workflow,  I'd have to "update" the distribution rather than create no ?
Otherwise after a subsequent sync:
pulp deb distribution create --name=${NAME} --base-path=${NAME} --publication=${PUB_HREF}
Error: {"base_path":["This field must be unique."],"name":["This field must be unique."]}

In the end I dont want to update what the client base URL for security updates.  I just want a "stable" version of updates during a patch rollout over several days.   Lmk if this/I make sense.

**Comment by kxs-jnadeau** [comment]
Many thanks for the help !
